In [1]:
# Import the necessary libraries
from PIL import Image
from numpy import asarray
import numpy as np
import os
import keras
from keras.layers import Dense, Conv2D, BatchNormalization, Activation
from keras.layers import AveragePooling2D, Input, Flatten
from tensorflow.keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint, LearningRateScheduler
from keras.callbacks import ReduceLROnPlateau
from keras.preprocessing.image import ImageDataGenerator
from keras.regularizers import l2
from keras import backend as K
from keras.models import Model
from keras.datasets import cifar10
import numpy as np
import os
from keras.utils import np_utils
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
# calculates f1 for 1:100 dataset with 95tp, 5fn, 55fp
from sklearn.metrics import f1_score
print('all imported')

all imported


In [2]:
def readImage(filePath):
    img = Image.open(filePath)
    
    size=(30,40)
    #resize image
    out = img.resize(size)

    # asarray() class is used to convert
    # PIL images into NumPy arrays
    numpydata = asarray(out)
    numpydata = np.repeat(numpydata[:, :, np.newaxis], 3, axis=2)
    # <class 'numpy.ndarray'>
    #print(type(numpydata))

    #  shape
    #print(numpydata.shape)
    return numpydata
print(readImage('data/disease/measles (1).png'))

[[[[ 76  84  95]
   [ 76  84  95]
   [ 76  84  95]]

  [[ 15  15  20]
   [ 15  15  20]
   [ 15  15  20]]

  [[  8   7  11]
   [  8   7  11]
   [  8   7  11]]

  ...

  [[ 16  14  25]
   [ 16  14  25]
   [ 16  14  25]]

  [[ 13  13  22]
   [ 13  13  22]
   [ 13  13  22]]

  [[  8   9  13]
   [  8   9  13]
   [  8   9  13]]]


 [[[ 88  96 107]
   [ 88  96 107]
   [ 88  96 107]]

  [[ 17  17  22]
   [ 17  17  22]
   [ 17  17  22]]

  [[  6   5   9]
   [  6   5   9]
   [  6   5   9]]

  ...

  [[ 15  13  23]
   [ 15  13  23]
   [ 15  13  23]]

  [[ 15  13  24]
   [ 15  13  24]
   [ 15  13  24]]

  [[ 10  10  16]
   [ 10  10  16]
   [ 10  10  16]]]


 [[[ 86  91  98]
   [ 86  91  98]
   [ 86  91  98]]

  [[ 14  13  17]
   [ 14  13  17]
   [ 14  13  17]]

  [[  5   4   7]
   [  5   4   7]
   [  5   4   7]]

  ...

  [[ 15  13  23]
   [ 15  13  23]
   [ 15  13  23]]

  [[ 15  13  23]
   [ 15  13  23]
   [ 15  13  23]]

  [[ 12  11  18]
   [ 12  11  18]
   [ 12  11  18]]]


 ...


 [[[157 162 

In [3]:
listFiles = os.listdir('data/disease/')
print(listFiles[:5])

['4164443_down-syndrome-down-syndrome-transparent-background-transparent-png.png', 'main-qimg-4c812ebe5c1bdc504625b6961032fd3b.png', 'measles (1).png', 'measles (10).jpg', 'measles (140).jpg']


In [4]:
#load Benign
listCancer = []
listResults = []
for elem in listFiles:
    img = readImage('data/disease/'+elem)
    listCancer += [img]
    listResults += [np.array([1])]
print(listCancer[:3])
print(img.shape)

[array([[[[243, 243, 243],
         [243, 243, 243],
         [243, 243, 243]],

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]],

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]],

        ...,

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]],

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]],

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]]],


       [[[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]],

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]],

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]],

        ...,

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]],

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]],

        [[242, 242, 242],
         [242, 242, 242],
         [242, 242, 242]]],


       

In [5]:
listFiles = os.listdir('data/health/')
print(listFiles[:5])
for elem in listFiles:
    img = readImage('data/health/'+elem)
    listResults += [np.array([0])]
    listCancer += [img]

['1 (1).jpeg', '1 (1).jpg', '1 (1).png', '1 (10).jpeg', '1 (10).jpg']


In [6]:
print(len(listCancer))

200


In [7]:
# Setting LR for different number of Epochs
def lr_schedule(epoch):
    lr = 1e-3
    if epoch > 180:
        lr *= 0.5e-3
    elif epoch > 160:
        lr *= 1e-3
    elif epoch > 120:
        lr *= 1e-2
    elif epoch > 80:
        lr *= 1e-1
    lr *= epoch / 100
    print('Learning rate: ', lr)
    return lr


In [8]:
# Basic ResNet Building Block
def resnet_layer(inputs, conv_first = False,
				num_filters = 16,
				kernel_size = 3,
				strides = 1,
				activation ='relu',
				batch_normalization = True):
	conv = Conv2D(num_filters,
				kernel_size = kernel_size,
				strides = strides,
				padding ='same',
				kernel_initializer ='he_normal',
				kernel_regularizer = l2(1e-4))

	x = inputs
	if conv_first:
		x = conv(x)
		if batch_normalization:
			x = BatchNormalization()(x)
		if activation is not None:
			x = Activation(activation)(x)
	else:
		if batch_normalization:
			x = BatchNormalization()(x)
		if activation is not None:
			x = Activation(activation)(x)
		x = conv(x)
	return x

In [9]:
# ResNet V2 architecture
def resnet_v2(input_shape, depth, num_classes = 10):
	if (depth - 2) % 9 != 0:
		raise ValueError('depth should be 9n + 2 (eg 56 or 110 in [b])')
	# Start model definition.
	num_filters_in = 16
	num_res_blocks = int((depth - 2) / 9)

	inputs = Input(shape = input_shape)
	# v2 performs Conv2D with BN-ReLU on input before splitting into 2 paths
	x = resnet_layer(inputs = inputs,num_filters = num_filters_in,conv_first = True)

	# Instantiate the stack of residual units
	for stage in range(3):
		for res_block in range(num_res_blocks):
			activation = 'relu'
			batch_normalization = True
			strides = 1
			if stage == 0:
				num_filters_out = num_filters_in * 4
				if res_block == 0: # first layer and first stage
					activation = None
					batch_normalization = False
			else:
				num_filters_out = num_filters_in * 2
				if res_block == 0: # first layer but not first stage
					strides = 2 # downsample

			# bottleneck residual unit
			y = resnet_layer(inputs = x,
							num_filters = num_filters_in,
							kernel_size = 1,
							strides = strides,
							activation = activation,
							batch_normalization = batch_normalization)
			y = resnet_layer(inputs = y,
							num_filters = num_filters_in,
							conv_first = False)
			y = resnet_layer(inputs = y,
							num_filters = num_filters_out,
							kernel_size = 1,
							conv_first = False)
			if res_block == 0:
				# linear projection residual shortcut connection to match
				# changed dims
				x = resnet_layer(inputs = x,
								num_filters = num_filters_out,
								kernel_size = 1,
								strides = strides,
								activation = None,
								batch_normalization = False)
			x = keras.layers.add([x, y])

		num_filters_in = num_filters_out

	# Add classifier on top.
	# v2 has BN-ReLU before Pooling
	x = BatchNormalization()(x)
	x = Activation('relu')(x)
	x = AveragePooling2D(pool_size = 8)(x)
	y = Flatten()(x)
	outputs = Dense(num_classes,
					activation ='softmax',
					kernel_initializer ='he_normal')(y)

	# Instantiate model.
	model = Model(inputs = inputs, outputs = outputs)
	return model

In [14]:
x_train=[]
y_train=[]
accs=[]
def main(pz, created_model):
    
    per = np.random.permutation(len(listCancer))
    ln = int(len(listCancer) * 0.55)
    x_train = []
    y_train = []
    x_test = []
    y_test = []
    positions = []
    #for i in range(ln):
    #    positions += [per[i]]
    val = 1
    while ln > 0:
        val = 1-val
        ln-=1
        for i in range(len(per)):
            if per[i] in positions:
                continue
            if listResults[per[i]] == np.array([val]):
                positions += [per[i]]
                break
    for i in range(len(listCancer)):
        if len(listCancer[i].shape)==3:
            continue
        if listCancer[i].shape[3] == 4:
            continue
        #print(listCancer[i].shape)
        if i in positions:
            x_train += [listCancer[i]]
            y_train += [listResults[i]]
        else:
            x_test += [listCancer[i]]
            y_test += [listResults[i]]
            
    ln = len(x_test) // 2
    
    x_valid = x_test[ln:]
    y_valid = y_test[ln:]
    
    print(len(x_valid))
    print(len(y_valid))
    
    
    x_test = x_test[:ln]
    y_test = y_test[:ln]
    
    
    x_train = np.array(x_train)
    x_train = x_train.reshape(len(x_train), 40, 30, 9)
    y_train = np.array(y_train)
    

    x_test = np.array(x_test)
    x_test = x_test.reshape(len(x_test), 40, 30, 9)
    y_test = np.array(y_test)
    
    x_valid = np.array(x_valid)
    x_valid = x_valid.reshape(len(x_valid), 40, 30, 9)
    y_valid = np.array(y_valid)
    
    
    batch_size = 64 # original ResNet paper uses batch_size = 128 for training
    epochs = 10
    data_augmentation = True
    num_classes = 10

    # Data Preprocessing
    subtract_pixel_mean = True
    n = 3

    # Select ResNet Version
    version = 2

    # Computed depth of
    if version == 1:
        depth = n * 6 + 2
    elif version == 2:
        depth = n * 9 + 2

    # Model name, depth and version
    model_type = 'ResNet % dv % d' % (depth, version)

    # use the data
    print(x_train[:3])
    print(y_train[:3])
    print(type(x_train[0]))
    print(type(x_train))
    print(type(y_train[0]))
    print(type(y_train))

    # Input image dimensions.
    input_shape = x_train.shape[1:]
    print(input_shape)

    # Normalize data.
    x_train = x_train.astype('float32') / 255
    x_test = x_test.astype('float32') / 255
    x_valid = x_test.astype('float32') / 255


    # Print Training and Test Samples
    print('x_train shape:', x_train.shape)
    print(x_train.shape[0], 'train samples')
    print(x_test.shape[0], 'test samples')
    print('y_train shape:', y_train.shape)

    # Convert class vectors to binary class matrices.
    y_train = keras.utils.np_utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.np_utils.to_categorical(y_test, num_classes)
    y_valid = keras.utils.np_utils.to_categorical(y_valid, num_classes)
    
    
    model = resnet_v2(input_shape = input_shape, depth = depth)

    model.compile(loss ='categorical_crossentropy',
                optimizer = Adam(learning_rate = lr_schedule(0)),
                metrics =['accuracy'])
    model.summary()
    print(model_type)

    # Prepare model model saving directory.
    save_dir = os.path.join(os.getcwd(), 'saved_models')
    model_name = 'cifar10_% s_model.{epoch:03d}.h5' % model_type
    if not os.path.isdir(save_dir):
        os.makedirs(save_dir)
    filepath = os.path.join(save_dir, model_name)

    # Prepare callbacks for model saving and for learning rate adjustment.
    checkpoint = ModelCheckpoint(filepath = filepath,
                                monitor ='val_acc',
                                verbose = 1,
                                save_best_only = True)

    lr_scheduler = LearningRateScheduler(lr_schedule)

    lr_reducer = ReduceLROnPlateau(factor = np.sqrt(0.1),
                                cooldown = 0,
                                patience = 5,
                                min_lr = 0.5e-6)

    callbacks = [checkpoint, lr_reducer, lr_scheduler]
    
    while len(y_valid) > len(x_valid):
        y_valid = np.delete(y_valid, len(y_valid)-1)

    # Run training, with or without data augmentation.
    if not data_augmentation:
        print('Not using data augmentation.')
        model.fit(x_train, y_train,
                batch_size = batch_size,
                epochs = epochs,
                validation_data =(x_test, y_test),
                shuffle = True,
                callbacks = callbacks)
    else:
        print('Using real-time data augmentation.')
        # This will do preprocessing and realtime data augmentation:
        datagen = ImageDataGenerator(
            # set input mean to 0 over the dataset
            featurewise_center = False,
            # set each sample mean to 0
            samplewise_center = False,
            # divide inputs by std of dataset
            featurewise_std_normalization = False,
            # divide each input by its std
            samplewise_std_normalization = False,
            # apply ZCA whitening
            zca_whitening = False,
            # epsilon for ZCA whitening
            zca_epsilon = 1e-06,
            # randomly rotate images in the range (deg 0 to 180)
            rotation_range = 0,
            # randomly shift images horizontally
            width_shift_range = 0.1,
            # randomly shift images vertically
            height_shift_range = 0.1,
            # set range for random shear
            shear_range = 0.,
            # set range for random zoom
            zoom_range = 0.,
            # set range for random channel shifts
            channel_shift_range = 0.,
            # set mode for filling points outside the input boundaries
            fill_mode ='nearest',
            # value used for fill_mode = "constant"
            cval = 0.,
            # randomly flip images
            horizontal_flip = True,
            # randomly flip images
            vertical_flip = False,
            # set rescaling factor (applied before any other transformation)
            rescale = None,
            # set function that will be applied on each input
            preprocessing_function = None,
            # image data format, either "channels_first" or "channels_last"
            data_format = None,
            # fraction of images reserved for validation (strictly between 0 and 1)
            validation_split = 0.1)

        # Compute quantities required for featurewise normalization
        # (std, mean, and principal components if ZCA whitening is applied).
        print('------------------')
        print(x_train)
        datagen.fit(x_train)

        # Fit the model on the batches generated by datagen.flow().
        model.fit_generator(datagen.flow(x_train, y_train, batch_size = batch_size),
                            validation_data =(x_valid, y_valid),
                            epochs = 100, verbose = 1, workers = 2,
                            callbacks = callbacks)

    # Score trained model.
    scores = model.evaluate(x_test, y_test, verbose = 1)
    print('Test loss:', scores[0])
    print('Test accuracy:', scores[1])
    ret = model.predict(x_test)
    result = []
    pred = []
    for a,b in zip(ret, y_test):
        pred+=[a.argmax(axis=-1)]
        result+=[b.argmax(axis=-1)]
    print(pred)
    print(result)
    precision = precision_score(result, pred, average='weighted')
    recall = recall_score(result, pred, average='weighted')
     # calculates f1 for 1:100 dataset with 95tp, 5fn, 55fp
    fmeasure = f1_score(result, pred, average='weighted')
    print('Precision: ', precision)
    print('Recall: ', recall)
    print('F1 Score: ', fmeasure)
    #precisions += [precision]
    #recalls += [recall]
    #model.save('saved_models/resNetV'+pz+'.h5')
    return [scores[1], precision, recall, fmeasure]

In [15]:
accs=[]
precisions = []
recalls = []
fmeasures = []
created_model = None
cnt = 0
while cnt < 10:
    vf=True
    #print(cnt)
    try:
        ret = main(cnt, created_model)
        cnt += 1
    except:
        vf = False
    if not vf:
        continue
    
    accs+=[ret[0]]
    precisions+=[ret[1]]
    recalls+=[ret[2]]
    fmeasures+=[ret[3]]
print(accs)
print(precisions)
print(recalls)
print(fmeasures)

29
29
[[[[ 76  84  95 ...  76  84  95]
   [ 15  15  20 ...  15  15  20]
   [  8   7  11 ...   8   7  11]
   ...
   [ 16  14  25 ...  16  14  25]
   [ 13  13  22 ...  13  13  22]
   [  8   9  13 ...   8   9  13]]

  [[ 88  96 107 ...  88  96 107]
   [ 17  17  22 ...  17  17  22]
   [  6   5   9 ...   6   5   9]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  24 ...  15  13  24]
   [ 10  10  16 ...  10  10  16]]

  [[ 86  91  98 ...  86  91  98]
   [ 14  13  17 ...  14  13  17]
   [  5   4   7 ...   5   4   7]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  23 ...  15  13  23]
   [ 12  11  18 ...  12  11  18]]

  ...

  [[157 162 174 ... 157 162 174]
   [159 165 176 ... 159 165 176]
   [155 158 159 ... 155 158 159]
   ...
   [126 136 168 ... 126 136 168]
   [145 153 178 ... 145 153 178]
   [150 157 180 ... 150 157 180]]

  [[158 162 174 ... 158 162 174]
   [158 164 177 ... 158 164 177]
   [160 167 179 ... 160 167 179]
   ...
   [134 144 172 ... 134 144 172]
   [143 151 177 ... 

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (72, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (72, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

2/2 [==============================] - 8s 2s/step - loss: 2.3974 - accuracy: 0.5278 - val_loss: 2.8400 - val_accuracy: 1.0000
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 2s/step - loss: 2.3965 - accuracy: 0.4722 - val_loss: 2.7963 - val_accuracy: 0.9655
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 443ms/step - loss: 2.3861 - accuracy: 0.5000 - val_loss: 2.7647 - val_accuracy: 0.0345
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 2s/step - loss: 2.3708 - accuracy: 0.5278 - val_loss: 2.7370 - val_accuracy: 0.0000e+00
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 2s 458ms/step - loss: 2.3567 - accuracy: 0.5000 - val_loss: 2.7116 - val_accuracy: 0.0000e+00
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 2s/step - loss: 2.2951 - accuracy: 0.6111 - val_loss: 2.6808 - val_accuracy: 0.0000e+00
Epoch 7/100
Learning rate:  6e-05
2/2 [=================

2/2 [==============================] - 2s 2s/step - loss: 1.0241 - accuracy: 0.9028 - val_loss: 1.1495 - val_accuracy: 1.0000
Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 3s 615ms/step - loss: 1.0402 - accuracy: 0.8611 - val_loss: 1.1374 - val_accuracy: 1.0000
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 3s 2s/step - loss: 0.9985 - accuracy: 0.9028 - val_loss: 1.1333 - val_accuracy: 1.0000
Epoch 37/100
Learning rate:  0.00035999999999999997
2/2 [==============================] - 2s 2s/step - loss: 0.9860 - accuracy: 0.8889 - val_loss: 1.0902 - val_accuracy: 1.0000
Epoch 38/100
Learning rate:  0.00037
2/2 [==============================] - 2s 441ms/step - loss: 0.9401 - accuracy: 0.8750 - val_loss: 1.0147 - val_accuracy: 1.0000
Epoch 39/100
Learning rate:  0.00038
2/2 [==============================] - 2s 467ms/step - loss: 0.9752 - accuracy: 0.8750 - val_loss: 0.9139 - val_accuracy: 1.0000
Epoch 40/100
Learning rate:  0.0003

Epoch 68/100
Learning rate:  0.00067
2/2 [==============================] - 2s 459ms/step - loss: 0.7853 - accuracy: 0.9444 - val_loss: 0.6503 - val_accuracy: 1.0000
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 2s 2s/step - loss: 0.7230 - accuracy: 0.9861 - val_loss: 0.9021 - val_accuracy: 1.0000
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 2s 489ms/step - loss: 0.6889 - accuracy: 0.9722 - val_loss: 1.1876 - val_accuracy: 1.0000
Epoch 71/100
Learning rate:  0.0007
2/2 [==============================] - 2s 461ms/step - loss: 0.6849 - accuracy: 0.9722 - val_loss: 1.3660 - val_accuracy: 1.0000
Epoch 72/100
Learning rate:  0.00071
2/2 [==============================] - 2s 454ms/step - loss: 0.6885 - accuracy: 0.9722 - val_loss: 1.6135 - val_accuracy: 1.0000
Epoch 73/100
Learning rate:  0.0007199999999999999
2/2 [==============================] - 2s 495ms/step - loss: 0.6893 - accuracy: 1.0000 - val_loss: 1.9467 - val_accuracy: 0

1/1 [==============================] - 0s 218ms/step - loss: 1.2892 - accuracy: 0.7241
Test loss: 1.2892245054244995
Test accuracy: 0.7241379022598267
[1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.871264367816092
Recall:  0.7241379310344828
F1 Score:  0.7436433298502263
30
30
[[[[  9   9   2 ...   9   9   2]
   [  6   6   2 ...   6   6   2]
   [  4   3   1 ...   4   3   1]
   ...
   [  0   1   1 ...   0   1   1]
   [  1   2   2 ...   1   2   2]
   [  9  10   7 ...   9  10   7]]

  [[  9   8   4 ...   9   8   4]
   [  9   9   4 ...   9   9   4]
   [  9   8   3 ...   9   8   3]
   ...
   [  1   1   1 ...   1   1   1]
   [  4   4   3 ...   4   4   3]
   [  4   5   3 ...   4   5   3]]

  [[ 26  23  14 ...  26  23  14]
   [ 33  27  15 ...  33  27  15]
   [ 45  37  24 ...  45  37  24]
   ...
   [  2   3   2 ...   2   3   2]
   [  2   2   2 ...   2   

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

2/2 [==============================] - 7s 3s/step - loss: 2.2187 - accuracy: 0.6286 - val_loss: 2.5777 - val_accuracy: 1.0000
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 2s/step - loss: 2.2194 - accuracy: 0.6286 - val_loss: 2.4017 - val_accuracy: 1.0000
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 375ms/step - loss: 2.2106 - accuracy: 0.6286 - val_loss: 2.2825 - val_accuracy: 1.0000
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 2s/step - loss: 2.1910 - accuracy: 0.6286 - val_loss: 2.2034 - val_accuracy: 1.0000
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 2s 533ms/step - loss: 2.1851 - accuracy: 0.6286 - val_loss: 2.1409 - val_accuracy: 1.0000
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 2s/step - loss: 2.1169 - accuracy: 0.6286 - val_loss: 2.0698 - val_accuracy: 1.0000
Epoch 7/100
Learning rate:  6e-05
2/2 [=============================

Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 2s 374ms/step - loss: 0.9654 - accuracy: 0.8714 - val_loss: 0.6956 - val_accuracy: 1.0000
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 2s 412ms/step - loss: 0.9748 - accuracy: 0.8857 - val_loss: 0.6865 - val_accuracy: 1.0000
Epoch 37/100
Learning rate:  0.00035999999999999997
2/2 [==============================] - 2s 396ms/step - loss: 0.9471 - accuracy: 0.8714 - val_loss: 0.6803 - val_accuracy: 1.0000
Epoch 38/100
Learning rate:  0.00037
2/2 [==============================] - 2s 2s/step - loss: 0.9474 - accuracy: 0.8429 - val_loss: 0.6525 - val_accuracy: 1.0000
Epoch 39/100
Learning rate:  0.00038
2/2 [==============================] - 2s 2s/step - loss: 0.9115 - accuracy: 0.8571 - val_loss: 0.6373 - val_accuracy: 1.0000
Epoch 40/100
Learning rate:  0.00039000000000000005
2/2 [==============================] - 2s 379ms/step - loss: 0.9503 - accuracy: 0.8571 - val_loss: 0.6301 - v

2/2 [==============================] - 2s 466ms/step - loss: 0.8013 - accuracy: 0.9143 - val_loss: 0.6230 - val_accuracy: 1.0000
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 3s 510ms/step - loss: 0.6986 - accuracy: 1.0000 - val_loss: 0.6051 - val_accuracy: 1.0000
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 2s 2s/step - loss: 0.7540 - accuracy: 0.9286 - val_loss: 0.5969 - val_accuracy: 1.0000
Epoch 71/100
Learning rate:  0.0007
2/2 [==============================] - 2s 518ms/step - loss: 0.7350 - accuracy: 0.9571 - val_loss: 0.5930 - val_accuracy: 1.0000
Epoch 72/100
Learning rate:  0.00071
2/2 [==============================] - 2s 2s/step - loss: 0.7413 - accuracy: 0.9571 - val_loss: 0.5912 - val_accuracy: 1.0000
Epoch 73/100
Learning rate:  0.0007199999999999999
2/2 [==============================] - 2s 501ms/step - loss: 0.7104 - accuracy: 0.9571 - val_loss: 0.5907 - val_accuracy: 1.0000
Epoch 74/100
Learning rate:  0.000

[1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.8888888888888888
Recall:  0.8333333333333334
F1 Score:  0.8380952380952381
29
29
[[[[  9   9   2 ...   9   9   2]
   [  6   6   2 ...   6   6   2]
   [  4   3   1 ...   4   3   1]
   ...
   [  0   1   1 ...   0   1   1]
   [  1   2   2 ...   1   2   2]
   [  9  10   7 ...   9  10   7]]

  [[  9   8   4 ...   9   8   4]
   [  9   9   4 ...   9   9   4]
   [  9   8   3 ...   9   8   3]
   ...
   [  1   1   1 ...   1   1   1]
   [  4   4   3 ...   4   4   3]
   [  4   5   3 ...   4   5   3]]

  [[ 26  23  14 ...  26  23  14]
   [ 33  27  15 ...  33  27  15]
   [ 45  37  24 ...  45  37  24]
   ...
   [  2   3   2 ...   2   3   2]
   [  2   2   2 ...   2   2   2]
   [  4   4   3 ...   4   4   3]]

  ...

  [[188 178 161 ... 188 178 161]
   [190 180 162 ... 190 180 162]
   [187 177 158 ... 187 177 1

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (73, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (73, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

2/2 [==============================] - ETA: 0s - loss: 2.4935 - accuracy: 0.287731
31
[[[[ 76  84  95 ...  76  84  95]
   [ 15  15  20 ...  15  15  20]
   [  8   7  11 ...   8   7  11]
   ...
   [ 16  14  25 ...  16  14  25]
   [ 13  13  22 ...  13  13  22]
   [  8   9  13 ...   8   9  13]]

  [[ 88  96 107 ...  88  96 107]
   [ 17  17  22 ...  17  17  22]
   [  6   5   9 ...   6   5   9]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  24 ...  15  13  24]
   [ 10  10  16 ...  10  10  16]]

  [[ 86  91  98 ...  86  91  98]
   [ 14  13  17 ...  14  13  17]
   [  5   4   7 ...   5   4   7]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  23 ...  15  13  23]
   [ 12  11  18 ...  12  11  18]]

  ...

  [[157 162 174 ... 157 162 174]
   [159 165 176 ... 159 165 176]
   [155 158 159 ... 155 158 159]
   ...
   [126 136 168 ... 126 136 168]
   [145 153 178 ... 145 153 178]
   [150 157 180 ... 150 157 180]]

  [[158 162 174 ... 158 162 174]
   [158 164 177 ... 158 164 177]
   [160 167 1

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (69, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (69, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '


Epoch 1/100
Learning rate:  0.0
2/2 [==============================] - ETA: 0s - loss: 3.0187 - accuracy: 0.0000e+0033
33
[[[[243 243 243 ... 243 243 243]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  ...

  [[243 242 244 ... 243 242 244]
   [245 242 248 ... 245 242 248]
   [250 250 253 ... 250 250 253]
   ...
   [214 218 239 ... 214 218 239]
   [205 209 233 ... 205 209 233]
   [213 215 234 ... 213 215 234]]

  [[238 236 241 ... 238 236 241]
   [235 23

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (65, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (65, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '


2/2 [==============================] - ETA: 0s - loss: 2.4396 - accuracy: 0.2462    30
30
[[[[243 243 243 ... 243 243 243]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  ...

  [[243 242 244 ... 243 242 244]
   [245 242 248 ... 245 242 248]
   [250 250 253 ... 250 250 253]
   ...
   [214 218 239 ... 214 218 239]
   [205 209 233 ... 205 209 233]
   [213 215 234 ... 213 215 234]]

  [[238 236 241 ... 238 236 241]
   [235 230 238 ... 235 230 238]
   [240 2

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '


2/2 [==============================] - 6s 3s/step - loss: 2.9723 - accuracy: 0.0429 - val_loss: 2.9140 - val_accuracy: 0.0000e+00
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 2s/step - loss: 2.9680 - accuracy: 0.0429 - val_loss: 2.9261 - val_accuracy: 0.0000e+00
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 2s/step - loss: 2.9530 - accuracy: 0.0714 - val_loss: 2.9221 - val_accuracy: 0.0000e+00
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 2s/step - loss: 2.9356 - accuracy: 0.0286 - val_loss: 2.9017 - val_accuracy: 0.0000e+00
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 2s 2s/step - loss: 2.9079 - accuracy: 0.0429 - val_loss: 2.8756 - val_accuracy: 0.0000e+00
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 2s/step - loss: 2.8741 - accuracy: 0.1000 - val_loss: 2.8427 - val_accuracy: 0.0000e+00
Epoch 7/100
Learning rate:  6e-05
2/2 [===========

2/2 [==============================] - 3s 462ms/step - loss: 1.0819 - accuracy: 0.8714 - val_loss: 0.8528 - val_accuracy: 1.0000
Epoch 32/100
Learning rate:  0.00031
2/2 [==============================] - 2s 434ms/step - loss: 1.1055 - accuracy: 0.8714 - val_loss: 0.8689 - val_accuracy: 1.0000
Epoch 33/100
Learning rate:  0.00032
2/2 [==============================] - 2s 2s/step - loss: 1.0407 - accuracy: 0.8571 - val_loss: 0.8789 - val_accuracy: 1.0000
Epoch 34/100
Learning rate:  0.00033
2/2 [==============================] - 2s 2s/step - loss: 1.0170 - accuracy: 0.8857 - val_loss: 0.8682 - val_accuracy: 1.0000
Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 2s 2s/step - loss: 0.9516 - accuracy: 0.9286 - val_loss: 0.8527 - val_accuracy: 1.0000
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 2s 405ms/step - loss: 0.9394 - accuracy: 0.9429 - val_loss: 0.8349 - val_accuracy: 1.0000
Epoch 37/100
Learning rate:  0.0003599999999999999

Epoch 65/100
Learning rate:  0.00064
2/2 [==============================] - 2s 2s/step - loss: 0.7491 - accuracy: 0.9429 - val_loss: 0.6004 - val_accuracy: 1.0000
Epoch 66/100
Learning rate:  0.0006500000000000001
2/2 [==============================] - 2s 393ms/step - loss: 0.7319 - accuracy: 0.9571 - val_loss: 0.5991 - val_accuracy: 1.0000
Epoch 67/100
Learning rate:  0.00066
2/2 [==============================] - 2s 400ms/step - loss: 0.7823 - accuracy: 0.9571 - val_loss: 0.5977 - val_accuracy: 1.0000
Epoch 68/100
Learning rate:  0.00067
2/2 [==============================] - 2s 2s/step - loss: 0.7121 - accuracy: 0.9571 - val_loss: 0.5965 - val_accuracy: 1.0000
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 2s 2s/step - loss: 0.7260 - accuracy: 0.9571 - val_loss: 0.5956 - val_accuracy: 1.0000
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 2s 390ms/step - loss: 0.8177 - accuracy: 0.9286 - val_loss: 0.5950 - val_accuracy: 1.0000

Epoch 98/100
Learning rate:  9.7e-05
2/2 [==============================] - 2s 395ms/step - loss: 0.6487 - accuracy: 1.0000 - val_loss: 0.5870 - val_accuracy: 1.0000
Epoch 99/100
Learning rate:  9.8e-05
2/2 [==============================] - 2s 430ms/step - loss: 0.6560 - accuracy: 1.0000 - val_loss: 0.5869 - val_accuracy: 1.0000
Epoch 100/100
Learning rate:  9.900000000000001e-05
1/1 [==============================] - 0s 201ms/step - loss: 1.4189 - accuracy: 0.7000
Test loss: 1.4188671112060547
Test accuracy: 0.699999988079071
[1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.7625
Recall:  0.7
F1 Score:  0.7123384253819036
29
29
[[[[ 76  84  95 ...  76  84  95]
   [ 15  15  20 ...  15  15  20]
   [  8   7  11 ...   8   7  11]
   ...
   [ 16  14  25 ...  16  14  25]
   [ 13  13  22 ...  13  13  22]
   [  8   9  13 ...   8   9  13]]

  [[ 88  

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (73, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (73, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

2/2 [==============================] - ETA: 0s - loss: 3.1219 - accuracy: 0.0000e+0030
30
[[[[243 243 243 ... 243 243 243]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  ...

  [[243 242 244 ... 243 242 244]
   [245 242 248 ... 245 242 248]
   [250 250 253 ... 250 250 253]
   ...
   [214 218 239 ... 214 218 239]
   [205 209 233 ... 205 209 233]
   [213 215 234 ... 213 215 234]]

  [[238 236 241 ... 238 236 241]
   [235 230 238 ... 235 230 238]
   [240 2

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '


2/2 [==============================] - 6s 1s/step - loss: 3.7744 - accuracy: 0.0000e+00 - val_loss: 2.9364 - val_accuracy: 0.0000e+00
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 403ms/step - loss: 3.7535 - accuracy: 0.0000e+00 - val_loss: 2.9515 - val_accuracy: 0.0000e+00
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 404ms/step - loss: 3.7471 - accuracy: 0.0000e+00 - val_loss: 2.9499 - val_accuracy: 0.0000e+00
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 2s/step - loss: 3.7289 - accuracy: 0.0000e+00 - val_loss: 2.9381 - val_accuracy: 0.0000e+00
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 2s 412ms/step - loss: 3.6908 - accuracy: 0.0000e+00 - val_loss: 2.9159 - val_accuracy: 0.0000e+00
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 2s/step - loss: 3.6479 - accuracy: 0.0000e+00 - val_loss: 2.8986 - val_accuracy: 0.0000e+00
Epoch 7/100
Learn

2/2 [==============================] - 2s 376ms/step - loss: 1.2426 - accuracy: 0.8000 - val_loss: 1.5884 - val_accuracy: 1.0000
Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 2s 420ms/step - loss: 1.1916 - accuracy: 0.8571 - val_loss: 1.6723 - val_accuracy: 1.0000
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 2s 2s/step - loss: 1.1219 - accuracy: 0.8571 - val_loss: 1.8342 - val_accuracy: 1.0000
Epoch 37/100
Learning rate:  0.00035999999999999997
2/2 [==============================] - 3s 540ms/step - loss: 1.1125 - accuracy: 0.8571 - val_loss: 2.2488 - val_accuracy: 0.0000e+00
Epoch 38/100
Learning rate:  0.00037
2/2 [==============================] - 2s 2s/step - loss: 1.0495 - accuracy: 0.8857 - val_loss: 2.9678 - val_accuracy: 0.0000e+00
Epoch 39/100
Learning rate:  0.00038
2/2 [==============================] - 2s 2s/step - loss: 0.9848 - accuracy: 0.9143 - val_loss: 3.6685 - val_accuracy: 0.0000e+00
Epoch 40/100
Learning r

2/2 [==============================] - 2s 2s/step - loss: 0.8178 - accuracy: 0.9000 - val_loss: 2.3342 - val_accuracy: 0.0000e+00
Epoch 68/100
Learning rate:  0.00067
2/2 [==============================] - 2s 2s/step - loss: 0.8179 - accuracy: 0.9000 - val_loss: 2.0172 - val_accuracy: 0.0000e+00
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 3s 2s/step - loss: 0.8094 - accuracy: 0.9429 - val_loss: 1.7063 - val_accuracy: 0.0000e+00
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 3s 457ms/step - loss: 0.7612 - accuracy: 0.9714 - val_loss: 1.1209 - val_accuracy: 1.0000
Epoch 71/100
Learning rate:  0.0007
2/2 [==============================] - 2s 2s/step - loss: 0.7984 - accuracy: 0.9286 - val_loss: 0.8977 - val_accuracy: 1.0000
Epoch 72/100
Learning rate:  0.00071
2/2 [==============================] - 2s 421ms/step - loss: 0.8362 - accuracy: 0.9429 - val_loss: 1.0714 - val_accuracy: 1.0000
Epoch 73/100
Learning rate:  0.00071999999

1/1 [==============================] - 0s 263ms/step - loss: 1.3157 - accuracy: 0.8333
Test loss: 1.315671443939209
Test accuracy: 0.8333333134651184
[1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.8928571428571428
Recall:  0.8333333333333334
F1 Score:  0.8401880141010576
30
30
[[[[ 30  95 105 ...  30  95 105]
   [ 31  97 107 ...  31  97 107]
   [ 30  96 106 ...  30  96 106]
   ...
   [ 26  91 103 ...  26  91 103]
   [ 25  92 102 ...  25  92 102]
   [ 24  91 101 ...  24  91 101]]

  [[ 27 111 122 ...  27 111 122]
   [ 27 111 123 ...  27 111 123]
   [ 28 111 123 ...  28 111 123]
   ...
   [ 22 107 119 ...  22 107 119]
   [ 22 108 118 ...  22 108 118]
   [ 23 108 119 ...  23 108 119]]

  [[ 24 105 116 ...  24 105 116]
   [ 25 107 118 ...  25 107 118]
   [ 28 108 119 ...  28 108 119]
   ...
   [ 26 107 117 ...  26 107 117]
   [ 23 105 115 ... 

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

2/2 [==============================] - 7s 1s/step - loss: 2.6387 - accuracy: 0.1000 - val_loss: 2.8907 - val_accuracy: 0.0000e+00
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 2s/step - loss: 2.6332 - accuracy: 0.0714 - val_loss: 2.8555 - val_accuracy: 0.0000e+00
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 381ms/step - loss: 2.6240 - accuracy: 0.0714 - val_loss: 2.8362 - val_accuracy: 0.0000e+00
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 472ms/step - loss: 2.6043 - accuracy: 0.0571 - val_loss: 2.8106 - val_accuracy: 0.0333
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 3s 483ms/step - loss: 2.5887 - accuracy: 0.0857 - val_loss: 2.7829 - val_accuracy: 0.3333
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 384ms/step - loss: 2.5560 - accuracy: 0.1143 - val_loss: 2.7508 - val_accuracy: 1.0000
Epoch 7/100
Learning rate:  6e-05
2/2 [===========

Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 2s 2s/step - loss: 0.9753 - accuracy: 0.9000 - val_loss: 0.9031 - val_accuracy: 1.0000
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 2s 2s/step - loss: 0.9840 - accuracy: 0.8714 - val_loss: 0.8902 - val_accuracy: 1.0000
Epoch 37/100
Learning rate:  0.00035999999999999997
2/2 [==============================] - 2s 2s/step - loss: 0.9231 - accuracy: 0.9000 - val_loss: 0.8496 - val_accuracy: 1.0000
Epoch 38/100
Learning rate:  0.00037
2/2 [==============================] - 2s 406ms/step - loss: 0.8814 - accuracy: 0.9286 - val_loss: 0.8080 - val_accuracy: 1.0000
Epoch 39/100
Learning rate:  0.00038
2/2 [==============================] - 2s 2s/step - loss: 0.8943 - accuracy: 0.9143 - val_loss: 0.7273 - val_accuracy: 1.0000
Epoch 40/100
Learning rate:  0.00039000000000000005
2/2 [==============================] - 2s 2s/step - loss: 0.8696 - accuracy: 0.9000 - val_loss: 0.6762 - val_accura

2/2 [==============================] - 2s 2s/step - loss: 0.7940 - accuracy: 0.9143 - val_loss: 0.5937 - val_accuracy: 1.0000
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 2s 2s/step - loss: 0.7568 - accuracy: 0.9286 - val_loss: 0.5952 - val_accuracy: 1.0000
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 2s 389ms/step - loss: 0.7483 - accuracy: 0.9429 - val_loss: 0.6038 - val_accuracy: 1.0000
Epoch 71/100
Learning rate:  0.0007
2/2 [==============================] - 2s 2s/step - loss: 0.7182 - accuracy: 0.9714 - val_loss: 0.6298 - val_accuracy: 1.0000
Epoch 72/100
Learning rate:  0.00071
2/2 [==============================] - 2s 391ms/step - loss: 0.7156 - accuracy: 0.9571 - val_loss: 0.6958 - val_accuracy: 1.0000
Epoch 73/100
Learning rate:  0.0007199999999999999
2/2 [==============================] - 2s 386ms/step - loss: 0.7206 - accuracy: 0.9571 - val_loss: 0.8401 - val_accuracy: 1.0000
Epoch 74/100
Learning rate:  0.00073


[1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.8
Recall:  0.8
F1 Score:  0.8
33
33
[[[[243 243 243 ... 243 243 243]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  ...

  [[243 242 244 ... 243 242 244]
   [245 242 248 ... 245 242 248]
   [250 250 253 ... 250 250 253]
   ...
   [214 218 239 ... 214 218 239]
 

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (65, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (65, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

2/2 [==============================] - ETA: 0s - loss: 3.3058 - accuracy: 0.0000e+0028
28
[[[[ 30  95 105 ...  30  95 105]
   [ 31  97 107 ...  31  97 107]
   [ 30  96 106 ...  30  96 106]
   ...
   [ 26  91 103 ...  26  91 103]
   [ 25  92 102 ...  25  92 102]
   [ 24  91 101 ...  24  91 101]]

  [[ 27 111 122 ...  27 111 122]
   [ 27 111 123 ...  27 111 123]
   [ 28 111 123 ...  28 111 123]
   ...
   [ 22 107 119 ...  22 107 119]
   [ 22 108 118 ...  22 108 118]
   [ 23 108 119 ...  23 108 119]]

  [[ 24 105 116 ...  24 105 116]
   [ 25 107 118 ...  25 107 118]
   [ 28 108 119 ...  28 108 119]
   ...
   [ 26 107 117 ...  26 107 117]
   [ 23 105 115 ...  23 105 115]
   [ 22 104 116 ...  22 104 116]]

  ...

  [[  7  29  34 ...   7  29  34]
   [ 87  67  56 ...  87  67  56]
   [179 128 119 ... 179 128 119]
   ...
   [195 132 133 ... 195 132 133]
   [119  77  72 ... 119  77  72]
   [ 50  35  35 ...  50  35  35]]

  [[  1  41  49 ...   1  41  49]
   [ 72  61  52 ...  72  61  52]
   [169 1

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (74, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (74, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '


2/2 [==============================] - 7s 3s/step - loss: 2.7675 - accuracy: 0.0541 - val_loss: 2.7748 - val_accuracy: 0.9643
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 2s/step - loss: 2.7779 - accuracy: 0.0405 - val_loss: 2.6040 - val_accuracy: 1.0000
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 2s/step - loss: 2.7372 - accuracy: 0.0946 - val_loss: 2.5062 - val_accuracy: 1.0000
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 549ms/step - loss: 2.7404 - accuracy: 0.0946 - val_loss: 2.4250 - val_accuracy: 1.0000
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 2s 522ms/step - loss: 2.7260 - accuracy: 0.0541 - val_loss: 2.3552 - val_accuracy: 1.0000
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 2s/step - loss: 2.6768 - accuracy: 0.1757 - val_loss: 2.2648 - val_accuracy: 1.0000
Epoch 7/100
Learning rate:  6e-05
2/2 [=============================

Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 2s 2s/step - loss: 0.9890 - accuracy: 0.8919 - val_loss: 0.6473 - val_accuracy: 1.0000
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 2s 2s/step - loss: 0.9417 - accuracy: 0.9324 - val_loss: 0.6499 - val_accuracy: 1.0000
Epoch 37/100
Learning rate:  0.00035999999999999997
2/2 [==============================] - 2s 2s/step - loss: 0.9649 - accuracy: 0.9054 - val_loss: 0.6583 - val_accuracy: 1.0000
Epoch 38/100
Learning rate:  0.00037
2/2 [==============================] - 2s 2s/step - loss: 0.9243 - accuracy: 0.9459 - val_loss: 0.6742 - val_accuracy: 1.0000
Epoch 39/100
Learning rate:  0.00038
2/2 [==============================] - 2s 2s/step - loss: 0.9062 - accuracy: 0.9324 - val_loss: 0.6705 - val_accuracy: 1.0000
Epoch 40/100
Learning rate:  0.00039000000000000005
2/2 [==============================] - 2s 2s/step - loss: 0.8679 - accuracy: 0.9324 - val_loss: 0.6723 - val_accuracy:

2/2 [==============================] - 2s 2s/step - loss: 0.6484 - accuracy: 1.0000 - val_loss: 0.5954 - val_accuracy: 1.0000
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 2s 2s/step - loss: 0.6455 - accuracy: 1.0000 - val_loss: 0.5943 - val_accuracy: 1.0000
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 2s 564ms/step - loss: 0.6899 - accuracy: 0.9730 - val_loss: 0.5948 - val_accuracy: 1.0000
Epoch 71/100
Learning rate:  0.0007
2/2 [==============================] - 2s 531ms/step - loss: 0.6547 - accuracy: 1.0000 - val_loss: 0.5962 - val_accuracy: 1.0000
Epoch 72/100
Learning rate:  0.00071
2/2 [==============================] - 2s 532ms/step - loss: 0.6432 - accuracy: 1.0000 - val_loss: 0.6021 - val_accuracy: 1.0000
Epoch 73/100
Learning rate:  0.0007199999999999999
2/2 [==============================] - 2s 2s/step - loss: 0.6423 - accuracy: 1.0000 - val_loss: 0.6142 - val_accuracy: 1.0000
Epoch 74/100
Learning rate:  0.00073


[0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.8472222222222222
Recall:  0.75
F1 Score:  0.747765006385696
27
27
[[[[243 243 243 ... 243 243 243]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  ...

  [[243 242 244 ... 243 242 244]
   [245 242 248 ... 245 242 248]
   [250 250 253 ... 250 250 253]
   ...
   [214 218 239 

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (77, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (77, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

2/2 [==============================] - ETA: 0s - loss: 3.5412 - accuracy: 0.0000e+0032
32
[[[[243 243 243 ... 243 243 243]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  ...

  [[243 242 244 ... 243 242 244]
   [245 242 248 ... 245 242 248]
   [250 250 253 ... 250 250 253]
   ...
   [214 218 239 ... 214 218 239]
   [205 209 233 ... 205 209 233]
   [213 215 234 ... 213 215 234]]

  [[238 236 241 ... 238 236 241]
   [235 230 238 ... 235 230 238]
   [240 2

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (67, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (67, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '


2/2 [==============================] - ETA: 0s - loss: 3.1438 - accuracy: 0.0000e+0029
29
[[[[243 243 243 ... 243 243 243]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  [[242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   ...
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]
   [242 242 242 ... 242 242 242]]

  ...

  [[243 242 244 ... 243 242 244]
   [245 242 248 ... 245 242 248]
   [250 250 253 ... 250 250 253]
   ...
   [214 218 239 ... 214 218 239]
   [205 209 233 ... 205 209 233]
   [213 215 234 ... 213 215 234]]

  [[238 236 241 ... 238 236 241]
   [235 230 238 ... 235 230 238]
   [240 2

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (72, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (72, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '


2/2 [==============================] - 7s 3s/step - loss: 3.3993 - accuracy: 0.0139 - val_loss: 2.8991 - val_accuracy: 0.0000e+00
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 458ms/step - loss: 3.4049 - accuracy: 0.0139 - val_loss: 2.9131 - val_accuracy: 0.0000e+00
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 451ms/step - loss: 3.3846 - accuracy: 0.0139 - val_loss: 2.9097 - val_accuracy: 0.0000e+00
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 2s/step - loss: 3.3526 - accuracy: 0.0000e+00 - val_loss: 2.9047 - val_accuracy: 0.0000e+00
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 2s 438ms/step - loss: 3.3539 - accuracy: 0.0139 - val_loss: 2.8926 - val_accuracy: 0.0000e+00
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 2s/step - loss: 3.2998 - accuracy: 0.0139 - val_loss: 2.8758 - val_accuracy: 0.0000e+00
Epoch 7/100
Learning rate:  6e-05
2/2

2/2 [==============================] - 2s 507ms/step - loss: 1.2320 - accuracy: 0.8194 - val_loss: 0.9575 - val_accuracy: 1.0000
Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 2s 2s/step - loss: 1.1885 - accuracy: 0.8333 - val_loss: 1.0201 - val_accuracy: 1.0000
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 2s 2s/step - loss: 1.1318 - accuracy: 0.8333 - val_loss: 1.1112 - val_accuracy: 1.0000
Epoch 37/100
Learning rate:  0.00035999999999999997
2/2 [==============================] - 2s 441ms/step - loss: 1.0904 - accuracy: 0.8611 - val_loss: 1.2270 - val_accuracy: 1.0000
Epoch 38/100
Learning rate:  0.00037
2/2 [==============================] - 2s 444ms/step - loss: 1.1473 - accuracy: 0.8194 - val_loss: 1.3378 - val_accuracy: 1.0000
Epoch 39/100
Learning rate:  0.00038
2/2 [==============================] - 2s 2s/step - loss: 1.0833 - accuracy: 0.8056 - val_loss: 1.4965 - val_accuracy: 1.0000
Epoch 40/100
Learning rate:  0.0003

2/2 [==============================] - 2s 2s/step - loss: 0.7843 - accuracy: 0.9306 - val_loss: 6.0695 - val_accuracy: 0.0000e+00
Epoch 68/100
Learning rate:  0.00067
2/2 [==============================] - 2s 447ms/step - loss: 0.7594 - accuracy: 0.9444 - val_loss: 4.8038 - val_accuracy: 0.0000e+00
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 2s 2s/step - loss: 0.7449 - accuracy: 0.9444 - val_loss: 3.0870 - val_accuracy: 0.0000e+00
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 2s 2s/step - loss: 0.8094 - accuracy: 0.9167 - val_loss: 1.6448 - val_accuracy: 0.0000e+00
Epoch 71/100
Learning rate:  0.0007
2/2 [==============================] - 2s 2s/step - loss: 0.8119 - accuracy: 0.9028 - val_loss: 3.2571 - val_accuracy: 0.0000e+00
Epoch 72/100
Learning rate:  0.00071
2/2 [==============================] - 2s 2s/step - loss: 0.8012 - accuracy: 0.9167 - val_loss: 4.3458 - val_accuracy: 0.0000e+00
Epoch 73/100
Learning rate:  0.00

1/1 [==============================] - 0s 248ms/step - loss: 0.7699 - accuracy: 0.9310
Test loss: 0.7698709964752197
Test accuracy: 0.931034505367279
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.9373040752351096
Recall:  0.9310344827586207
F1 Score:  0.9283661740558292
26
26
[[[[ 76  84  95 ...  76  84  95]
   [ 15  15  20 ...  15  15  20]
   [  8   7  11 ...   8   7  11]
   ...
   [ 16  14  25 ...  16  14  25]
   [ 13  13  22 ...  13  13  22]
   [  8   9  13 ...   8   9  13]]

  [[ 88  96 107 ...  88  96 107]
   [ 17  17  22 ...  17  17  22]
   [  6   5   9 ...   6   5   9]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  24 ...  15  13  24]
   [ 10  10  16 ...  10  10  16]]

  [[ 86  91  98 ...  86  91  98]
   [ 14  13  17 ...  14  13  17]
   [  5   4   7 ...   5   4   7]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  23 ...  15  1

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (78, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (78, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

Epoch 1/100
Learning rate:  0.0
2/2 [==============================] - 6s 1s/step - loss: 3.1644 - accuracy: 0.0128 - val_loss: 3.0009 - val_accuracy: 0.0000e+00
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 2s/step - loss: 3.1722 - accuracy: 0.0128 - val_loss: 3.0581 - val_accuracy: 0.0000e+00
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 735ms/step - loss: 3.1318 - accuracy: 0.0128 - val_loss: 3.0893 - val_accuracy: 0.0000e+00
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 2s/step - loss: 3.1096 - accuracy: 0.0128 - val_loss: 3.1141 - val_accuracy: 0.0000e+00
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 2s 630ms/step - loss: 3.0956 - accuracy: 0.0256 - val_loss: 3.1291 - val_accuracy: 0.0000e+00
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 654ms/step - loss: 3.0592 - accuracy: 0.0256 - val_loss: 3.1374 - val_accuracy: 0.0000e+00
Epoch 7/1

Epoch 34/100
Learning rate:  0.00033
2/2 [==============================] - 2s 2s/step - loss: 1.0799 - accuracy: 0.8462 - val_loss: 3.2677 - val_accuracy: 0.0000e+00
Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 2s 632ms/step - loss: 1.0579 - accuracy: 0.8205 - val_loss: 2.8662 - val_accuracy: 0.0000e+00
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 2s 628ms/step - loss: 0.9991 - accuracy: 0.8846 - val_loss: 2.4524 - val_accuracy: 0.0000e+00
Epoch 37/100
Learning rate:  0.00035999999999999997
2/2 [==============================] - 2s 618ms/step - loss: 0.9828 - accuracy: 0.9103 - val_loss: 1.9946 - val_accuracy: 0.0000e+00
Epoch 38/100
Learning rate:  0.00037
2/2 [==============================] - 3s 920ms/step - loss: 0.9635 - accuracy: 0.8974 - val_loss: 1.5785 - val_accuracy: 1.0000
Epoch 39/100
Learning rate:  0.00038
2/2 [==============================] - 3s 2s/step - loss: 0.9005 - accuracy: 0.9359 - val_loss: 1.3877 - 

2/2 [==============================] - 3s 750ms/step - loss: 0.7948 - accuracy: 0.9359 - val_loss: 0.6198 - val_accuracy: 1.0000
Epoch 68/100
Learning rate:  0.00067
2/2 [==============================] - 2s 2s/step - loss: 0.7421 - accuracy: 0.9615 - val_loss: 0.6149 - val_accuracy: 1.0000
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 2s 644ms/step - loss: 0.6888 - accuracy: 0.9872 - val_loss: 0.6065 - val_accuracy: 1.0000
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 2s 629ms/step - loss: 0.6736 - accuracy: 0.9872 - val_loss: 0.6021 - val_accuracy: 1.0000
Epoch 71/100
Learning rate:  0.0007
2/2 [==============================] - 2s 657ms/step - loss: 0.6758 - accuracy: 0.9744 - val_loss: 0.6008 - val_accuracy: 1.0000
Epoch 72/100
Learning rate:  0.00071
2/2 [==============================] - 2s 612ms/step - loss: 0.6724 - accuracy: 0.9872 - val_loss: 0.6020 - val_accuracy: 1.0000
Epoch 73/100
Learning rate:  0.00071999999999

1/1 [==============================] - 0s 233ms/step - loss: 0.8102 - accuracy: 0.9231
Test loss: 0.8102356195449829
Test accuracy: 0.9230769276618958
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.9311740890688258
Recall:  0.9230769230769231
F1 Score:  0.9204059829059829
31
31
[[[[ 76  84  95 ...  76  84  95]
   [ 15  15  20 ...  15  15  20]
   [  8   7  11 ...   8   7  11]
   ...
   [ 16  14  25 ...  16  14  25]
   [ 13  13  22 ...  13  13  22]
   [  8   9  13 ...   8   9  13]]

  [[ 88  96 107 ...  88  96 107]
   [ 17  17  22 ...  17  17  22]
   [  6   5   9 ...   6   5   9]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  24 ...  15  13  24]
   [ 10  10  16 ...  10  10  16]]

  [[ 86  91  98 ...  86  91  98]
   [ 14  13  17 ...  14  13  17]
   [  5   4   7 ...   5   4   7]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  23 ...  15  13  23]
   [ 12  1

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (68, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (68, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

2/2 [==============================] - 7s 1s/step - loss: 2.5570 - accuracy: 0.3529 - val_loss: 2.8542 - val_accuracy: 0.0645
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 382ms/step - loss: 2.6066 - accuracy: 0.3382 - val_loss: 2.8088 - val_accuracy: 0.0968
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 359ms/step - loss: 2.5940 - accuracy: 0.3235 - val_loss: 2.7577 - val_accuracy: 0.9032
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 352ms/step - loss: 2.5520 - accuracy: 0.3382 - val_loss: 2.7054 - val_accuracy: 1.0000
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 2s 2s/step - loss: 2.5144 - accuracy: 0.3382 - val_loss: 2.6716 - val_accuracy: 1.0000
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 2s/step - loss: 2.4815 - accuracy: 0.3529 - val_loss: 2.6170 - val_accuracy: 1.0000
Epoch 7/100
Learning rate:  6e-05
2/2 [==========================

Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 2s 2s/step - loss: 1.0588 - accuracy: 0.8971 - val_loss: 0.7361 - val_accuracy: 1.0000
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 2s 2s/step - loss: 1.0916 - accuracy: 0.8529 - val_loss: 0.7655 - val_accuracy: 1.0000
Epoch 37/100
Learning rate:  0.00035999999999999997
2/2 [==============================] - 2s 372ms/step - loss: 1.0632 - accuracy: 0.8824 - val_loss: 0.7870 - val_accuracy: 1.0000
Epoch 38/100
Learning rate:  0.00037
2/2 [==============================] - 2s 2s/step - loss: 1.0559 - accuracy: 0.8824 - val_loss: 0.8195 - val_accuracy: 1.0000
Epoch 39/100
Learning rate:  0.00038
2/2 [==============================] - 2s 403ms/step - loss: 1.0470 - accuracy: 0.8824 - val_loss: 0.8359 - val_accuracy: 1.0000
Epoch 40/100
Learning rate:  0.00039000000000000005
2/2 [==============================] - 2s 391ms/step - loss: 0.9926 - accuracy: 0.8971 - val_loss: 0.8405 - val_

Epoch 68/100
Learning rate:  0.00067
2/2 [==============================] - 2s 335ms/step - loss: 0.7210 - accuracy: 0.9853 - val_loss: 0.6300 - val_accuracy: 1.0000
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 1s 1s/step - loss: 0.7285 - accuracy: 0.9559 - val_loss: 0.5997 - val_accuracy: 1.0000
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 2s 293ms/step - loss: 0.7642 - accuracy: 0.9118 - val_loss: 0.5975 - val_accuracy: 1.0000
Epoch 71/100
Learning rate:  0.0007
2/2 [==============================] - 2s 283ms/step - loss: 0.7361 - accuracy: 0.9559 - val_loss: 0.5969 - val_accuracy: 1.0000
Epoch 72/100
Learning rate:  0.00071
2/2 [==============================] - 1s 1s/step - loss: 0.7662 - accuracy: 0.9118 - val_loss: 0.5965 - val_accuracy: 1.0000
Epoch 73/100
Learning rate:  0.0007199999999999999
2/2 [==============================] - 1s 1s/step - loss: 0.7674 - accuracy: 0.9265 - val_loss: 0.5962 - val_accuracy: 1.0000


[1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.815994623655914
Recall:  0.7096774193548387
F1 Score:  0.7278023519257741
30
30
[[[[ 76  84  95 ...  76  84  95]
   [ 15  15  20 ...  15  15  20]
   [  8   7  11 ...   8   7  11]
   ...
   [ 16  14  25 ...  16  14  25]
   [ 13  13  22 ...  13  13  22]
   [  8   9  13 ...   8   9  13]]

  [[ 88  96 107 ...  88  96 107]
   [ 17  17  22 ...  17  17  22]
   [  6   5   9 ...   6   5   9]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  24 ...  15  13  24]
   [ 10  10  16 ...  10  10  16]]

  [[ 86  91  98 ...  86  91  98]
   [ 14  13  17 ...  14  13  17]
   [  5   4   7 ...   5   4   7]
   ...
   [ 15  13  23 ...  15  13  23]
   [ 15  13  23 ...  15  13  23]
   [ 12  11  18 ...  12  11  18]]

  ...

  [[157 162 174 ... 157 162 174]
   [159 165 176 ... 159 165 176]
   [155 158 159 ... 155 

c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\image_data_generator.py:938: UserWarning: Expected input to be images (as Numpy array) following the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn(
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras_preprocessing\image\numpy_array_iterator.py:129: UserWarning: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3, or 4 channels on axis 3. However, it was passed an array with shape (70, 40, 30, 9) (9 channels).
  warnings.warn('NumpyArrayIterator is set to use the '
c:\users\patcas rares\appdata\local\programs\python\python39\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and wil

2/2 [==============================] - 6s 2s/step - loss: 3.3289 - accuracy: 0.0286 - val_loss: 2.9949 - val_accuracy: 0.0000e+00
Epoch 2/100
Learning rate:  1e-05
2/2 [==============================] - 2s 2s/step - loss: 3.3343 - accuracy: 0.0286 - val_loss: 3.0326 - val_accuracy: 0.0000e+00
Epoch 3/100
Learning rate:  2e-05
2/2 [==============================] - 2s 315ms/step - loss: 3.3455 - accuracy: 0.0286 - val_loss: 3.0510 - val_accuracy: 0.0000e+00
Epoch 4/100
Learning rate:  3e-05
2/2 [==============================] - 2s 307ms/step - loss: 3.3208 - accuracy: 0.0286 - val_loss: 3.0548 - val_accuracy: 0.0000e+00
Epoch 5/100
Learning rate:  4e-05
2/2 [==============================] - 2s 309ms/step - loss: 3.2920 - accuracy: 0.0286 - val_loss: 3.0508 - val_accuracy: 0.0000e+00
Epoch 6/100
Learning rate:  5e-05
2/2 [==============================] - 2s 297ms/step - loss: 3.2826 - accuracy: 0.0286 - val_loss: 3.0416 - val_accuracy: 0.0000e+00
Epoch 7/100
Learning rate:  6e-05
2/2 

2/2 [==============================] - 2s 343ms/step - loss: 1.2386 - accuracy: 0.8000 - val_loss: 2.8196 - val_accuracy: 0.0000e+00
Epoch 35/100
Learning rate:  0.00034
2/2 [==============================] - 2s 304ms/step - loss: 1.2413 - accuracy: 0.8000 - val_loss: 2.8841 - val_accuracy: 0.0000e+00
Epoch 36/100
Learning rate:  0.00035
2/2 [==============================] - 2s 1s/step - loss: 1.1737 - accuracy: 0.8143 - val_loss: 2.9492 - val_accuracy: 0.0000e+00
Epoch 37/100
Learning rate:  0.00035999999999999997
2/2 [==============================] - 2s 1s/step - loss: 1.1527 - accuracy: 0.8143 - val_loss: 3.0072 - val_accuracy: 0.0000e+00
Epoch 38/100
Learning rate:  0.00037
2/2 [==============================] - 2s 321ms/step - loss: 1.1172 - accuracy: 0.8571 - val_loss: 3.0961 - val_accuracy: 0.0000e+00
Epoch 39/100
Learning rate:  0.00038
2/2 [==============================] - 2s 1s/step - loss: 1.1470 - accuracy: 0.8000 - val_loss: 3.1694 - val_accuracy: 0.0000e+00
Epoch 40/10

2/2 [==============================] - 2s 1s/step - loss: 0.7563 - accuracy: 0.9571 - val_loss: 0.5964 - val_accuracy: 1.0000
Epoch 68/100
Learning rate:  0.00067
2/2 [==============================] - 2s 313ms/step - loss: 0.7437 - accuracy: 0.9571 - val_loss: 0.5960 - val_accuracy: 1.0000
Epoch 69/100
Learning rate:  0.00068
2/2 [==============================] - 2s 1s/step - loss: 0.7648 - accuracy: 0.9571 - val_loss: 0.5956 - val_accuracy: 1.0000
Epoch 70/100
Learning rate:  0.00069
2/2 [==============================] - 1s 1s/step - loss: 0.7236 - accuracy: 0.9714 - val_loss: 0.5951 - val_accuracy: 1.0000
Epoch 71/100
Learning rate:  0.0007
2/2 [==============================] - 2s 328ms/step - loss: 0.7001 - accuracy: 1.0000 - val_loss: 0.5947 - val_accuracy: 1.0000
Epoch 72/100
Learning rate:  0.00071
2/2 [==============================] - 2s 321ms/step - loss: 0.7297 - accuracy: 0.9714 - val_loss: 0.5942 - val_accuracy: 1.0000
Epoch 73/100
Learning rate:  0.0007199999999999999


1/1 [==============================] - 0s 161ms/step - loss: 1.6228 - accuracy: 0.6000
Test loss: 1.6228071451187134
Test accuracy: 0.6000000238418579
[0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
Precision:  0.84
Recall:  0.6
F1 Score:  0.6107142857142858
[0.7241379022598267, 0.8333333134651184, 0.699999988079071, 0.8333333134651184, 0.800000011920929, 0.75, 0.931034505367279, 0.9230769276618958, 0.7096773982048035, 0.6000000238418579]
[0.871264367816092, 0.8888888888888888, 0.7625, 0.8928571428571428, 0.8, 0.8472222222222222, 0.9373040752351096, 0.9311740890688258, 0.815994623655914, 0.84]
[0.7241379310344828, 0.8333333333333334, 0.7, 0.8333333333333334, 0.8, 0.75, 0.9310344827586207, 0.9230769230769231, 0.7096774193548387, 0.6]
[0.7436433298502263, 0.8380952380952381, 0.7123384253819036, 0.8401880141010576, 0.8, 0.747765006385696, 0.9283661740558292

In [18]:
print(len(accs))
print('accs: ', accs)
print('precisions: ', precisions)
print('recalls: ', recalls)
print('fmeasures: ', fmeasures)

10
accs:  [0.7241379022598267, 0.8333333134651184, 0.699999988079071, 0.8333333134651184, 0.800000011920929, 0.75, 0.931034505367279, 0.9230769276618958, 0.7096773982048035, 0.6000000238418579]
precisions:  [0.871264367816092, 0.8888888888888888, 0.7625, 0.8928571428571428, 0.8, 0.8472222222222222, 0.9373040752351096, 0.9311740890688258, 0.815994623655914, 0.84]
recalls:  [0.7241379310344828, 0.8333333333333334, 0.7, 0.8333333333333334, 0.8, 0.75, 0.9310344827586207, 0.9230769230769231, 0.7096774193548387, 0.6]
fmeasures:  [0.7436433298502263, 0.8380952380952381, 0.7123384253819036, 0.8401880141010576, 0.8, 0.747765006385696, 0.9283661740558292, 0.9204059829059829, 0.7278023519257741, 0.6107142857142858]


In [19]:
import numpy as np
import scipy.stats as st

#define sample data
data = accs

#create 95% confidence interval for population mean weight
st.t.interval(alpha=0.95, df=len(data)-1, loc=np.mean(data), scale=st.sem(data))

(0.7061421141092344, 0.8547765627439455)

In [1]:
accs=  [0.6153846383094788, 0.8571428656578064, 0.6428571343421936, 0.692307710647583, 0.6666666865348816, 0.6666666865348816, 0.5, 1.0, 0.7142857313156128, 0.6153846383094788]
precisions=  [0.8557692307692307, 0.9142857142857144, 0.8660714285714286, 1.0, 0.875, 0.8148148148148149, 0.888888888888889, 1.0, 0.8571428571428571, 0.8901098901098901]
recalls=  [0.6153846153846154, 0.8571428571428571, 0.6428571428571429, 0.6923076923076923, 0.6666666666666666, 0.6666666666666666, 0.5, 1.0, 0.7142857142857143, 0.6153846153846154]
fmeasures=  [0.6386946386946387, 0.8678571428571429, 0.6715049656226126, 0.8181818181818181, 0.6985645933014354, 0.6476190476190476, 0.5561497326203209, 1.0, 0.7261904761904762, 0.6656611362493715]

In [20]:
import numpy as np
import scipy.stats as st

#define sample data
data = accs

#create 95% confidence interval for population mean weight
print(st.t.interval(alpha=0.95, df=len(data)-1, loc=np.mean(data), scale=st.sem(data)))

data = precisions

#create 95% confidence interval for population mean weight
print(st.t.interval(alpha=0.95, df=len(data)-1, loc=np.mean(data), scale=st.sem(data)))

data = recalls

#create 95% confidence interval for population mean weight
print(st.t.interval(alpha=0.95, df=len(data)-1, loc=np.mean(data), scale=st.sem(data)))

data = fmeasures

#create 95% confidence interval for population mean weight
print(st.t.interval(alpha=0.95, df=len(data)-1, loc=np.mean(data), scale=st.sem(data)))

(0.7061421141092344, 0.8547765627439455)
(0.818343629247924, 0.899097452700915)
(0.7061421194747853, 0.8547765651035212)
(0.716612808769828, 0.857250952913371)
